"""FastAPI server exposing the AG-UI agents:

  POST /fixed/   . fixed-schema PDF dashboard agent (pdf-analyst)
  POST /dynamic/ . dynamic A2UI surfaces generated at runtime
  POST /legal/   . contract-review copilot (legal-contract-review example)

Run with:  uvicorn main:app --port 8123 --reload
"""
from __future__ import annotations

import importlib.util
import logging
import os
import sys
from pathlib import Path

import uvicorn
from ag_ui_langgraph import add_langgraph_fastapi_endpoint
from copilotkit import LangGraphAGUIAgent
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

load_dotenv()

# Patch ag-ui-langgraph's multimodal converter so PDF text shipped via
# CopilotChat attachments survives the trip to the model (Gemini via the
# native Google Gen AI SDK; the break is provider-agnostic — see
# src/multimodal_middleware.py). Must run BEFORE the agent graphs are
# imported so the agents pick up the patched converter at first message
# conversion.
from src.multimodal_middleware import install as _install_doc_inlining  # noqa: E402

_install_doc_inlining()

from src.dynamic_agent import graph as dynamic_graph  # noqa: E402
from src.fixed_agent import graph as fixed_graph  # noqa: E402
from src.robot_state import router as robot_router  # noqa: E402

app = FastAPI(title="A2UI Demo Agents")

app.include_router(robot_router)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# LangGraph's default recursion_limit is 25. ag_ui_langgraph builds its own
# RunnableConfig per run, which overrides any `.with_config()` we bind at
# compile time on the graph. Pass recursion_limit here so it's honored.
# 50 is plenty for our two-tool flow; bump higher only if a deeper agent
# loop is genuinely needed.
_AGENT_CONFIG = {"recursion_limit": 100}

add_langgraph_fastapi_endpoint(
    app=app,
    agent=LangGraphAGUIAgent(
        name="fixed_agent",
        description="Fixed-schema PDF dashboard agent (pdf-analyst).",
        graph=fixed_graph,
        config=_AGENT_CONFIG,
    ),
    path="/fixed",
)

add_langgraph_fastapi_endpoint(
    app=app,
    agent=LangGraphAGUIAgent(
        name="dynamic_agent",
        description="Dynamic A2UI surfaces generated by a secondary LLM.",
        graph=dynamic_graph,
        config=_AGENT_CONFIG,
    ),
    path="/dynamic",
)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# /legal — contract-review copilot from the legal-contract-review example.
#
# That example's graph lives OUTSIDE this app's package, at
# other-examples/legal-contract-review/agent/graph.py. Its graph.py injects
# its own directory into sys.path and imports a sibling `tools` module
# (bare `from tools import ...`) — see the import note at the top of that
# file. To honor that contract we:
#   1. Inject the legal agent dir into sys.path so its `from tools import`
#      resolves to its own sibling tools.py.
#   2. Load graph.py by absolute file path (importlib) rather than a bare
#      `import graph`, so the generic module name `graph` can't collide
#      with anything in this app.
#
# This wiring is deliberately defensive: the cross-example sys.path dance is
# fragile, so the whole registration is wrapped in try/except. If it fails,
# we log a warning and skip /legal — the /fixed and /dynamic endpoints above
# must always import cleanly regardless of the legal example's state.
_LEGAL_AGENT_DIR = (
    Path(__file__).resolve().parent.parent
    / "other-examples"
    / "legal-contract-review"
    / "agent"
)

_legal_registered = False
try:
    if str(_LEGAL_AGENT_DIR) not in sys.path:
        # Prepend so the legal graph's own `from tools import ...` resolves
        # to its sibling tools.py and not some other `tools` on the path.
        sys.path.insert(0, str(_LEGAL_AGENT_DIR))

    _legal_spec = importlib.util.spec_from_file_location(
        "legal_review_graph", _LEGAL_AGENT_DIR / "graph.py"
    )
    if _legal_spec is None or _legal_spec.loader is None:
        raise ImportError(f"cannot load legal graph from {_LEGAL_AGENT_DIR / 'graph.py'}")
    _legal_module = importlib.util.module_from_spec(_legal_spec)
    _legal_spec.loader.exec_module(_legal_module)
    legal_graph = _legal_module.graph

    add_langgraph_fastapi_endpoint(
        app=app,
        agent=LangGraphAGUIAgent(
            name="legal_agent",
            description="Contract-review copilot (legal-contract-review example).",
            graph=legal_graph,
            config=_AGENT_CONFIG,
        ),
        path="/legal",
    )
    _legal_registered = True
except Exception as exc:  # noqa: BLE001 — never let /legal break /fixed + /dynamic
    logging.getLogger(__name__).warning(
        "Skipping /legal endpoint — failed to load legal graph from %s: %s",
        _LEGAL_AGENT_DIR,
        exc,
    )


@app.get("/")
def root():
    agents = {
        "fixed_agent": "/fixed/",
        "dynamic_agent": "/dynamic/",
    }
    if _legal_registered:
        agents["legal_agent"] = "/legal/"
    return {
        "ok": True,
        "agents": agents,
    }


def main():
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(os.environ.get("PORT", "8123")),
        reload=True,
    )


if __name__ == "__main__":
    main()
